TOP   =  1
UP    =  TOP
BOTTOM= -1
DOWN  = BOTTOM
LEFT  =  2
RIGHT = -2

DIRS = { UP, DOWN, LEFT, RIGHT }

CELLSIZE = 128
WALLSIZE =   8
WALLPERC =  WALLSIZE / CELLSIZE
PRIO_BACK =   10
PRIO_WALL =  300
PRIO_PORTAL = 400
MARKER_PRIO = 900
SIGHT_RANGE = 6
PORTAL_FONT_SIZE = 30

DEFAULT_WIDTH = 64
DEFAULT_HEIGHT = 32
DEFAULT_BACKGROUND = "DEFAULT.png"

JUMP_STRENGTH = 6
GRAV_STRENGTH = 2
AIR_ACCEL = 1
FLOOR_ACCEL = 6
FLOOR_SPEED = 1
VEL_CAP = 4
FRICTION = 4
